import DS from 'ember-data';

export default DS.Model.extend({
	colorExt: DS.attr('string'),
	colorInt: DS.attr('string'),
	grade: DS.attr('number'),
	make: DS.attr(),
	model: DS.attr(),
	odometer: DS.attr(),
	optionsList: DS.attr(),
	trim: DS.attr(),
	interiorList: DS.attr(),
	categories: DS.attr(),
	warrantyBasicMiles: DS.attr('number'),
	warrantyPowertrainMiles: DS.attr('number'),
	damagesList: DS.attr(),
	mpg: DS.attr(),
	price: DS.attr(),
	warrantyBasicYears: DS.attr('number'),
	interiorOdor: DS.attr('string'),
	drivenWheels: DS.attr(),
	imageList: DS.attr(),
	mechanicalList: DS.attr(),
	name: DS.attr('string'),
	expirationDt: DS.attr(),
	warrantyPowertrainYears: DS.attr('number'),
	numOfDoors: DS.attr('number'),
	year: DS.attr('number'),
	fuelType: DS.attr('string'),
	vin: DS.attr('string'),
	keyList: DS.attr(),
	engine: DS.attr(),
	tireDict: DS.attr(),
	transmission: DS.attr('string'),
	edmundsReview: DS.attr(),
	//scatterContent: DS.attr(),
});